-- 코드를 입력하세요
-- SELECT PRODUCT_CODE, sum(SALES_AMOUNT)*PRICE as SALES from PRODUCT p inner join OFFLINE_SALE o
-- on p.PRODUCT_ID = o.PRODUCT_ID
-- group by PRODUCT_CODE,SALES_AMOUNT,PRICE
-- order by SALES desc,PRODUCT_CODE asc

SELECT PRODUCT_CODE, sum(SALES_AMOUNT)*PRICE as SALES from PRODUCT p inner join OFFLINE_SALE o
on p.PRODUCT_ID = o.PRODUCT_ID
group by PRODUCT_CODE,PRICE
order by SALES desc,PRODUCT_CODE asc
